import AppKit
import Foundation

/// Pano geçmişindeki tek bir girdi.
///
/// Görseller doğrudan JSON'a gömülmüyor — yalnızca dosya adı tutuluyor,
/// gerçek veri `ClipboardHistoryStore`'un yönettiği ayrı bir klasörde.
struct ClipboardEntry: Identifiable, Codable, Equatable, Sendable {
    enum Kind: String, Codable, Sendable { case text, image }

    let id: UUID
    let kind: Kind
    var text: String?
    var imageFileName: String?
    let createdAt: Date
}

/// Sistem panosunu izleyip metin/görsel geçmişi biriktirir.
///
/// macOS panoya "değişti" bildirimi göndermiyor — tek güvenilir yol
/// `NSPasteboard.changeCount`'u düzenli aralıklarla yoklamak
/// (`NetworkHistoryStore`'daki örneklemeyle aynı kalıp). Kendi
/// "panoya geri kopyala" yazışımızı yeni bir geçmiş girdisi sanmamak için
/// sayaç o yazımdan hemen sonra da güncelleniyor.
@MainActor
@Observable
final class ClipboardHistoryStore {
    static let shared = ClipboardHistoryStore()

    private(set) var entries: [ClipboardEntry] = []

    private static let pollInterval: Duration = .milliseconds(700)
    /// Sınırsız birikim disk ve bellek açısından anlamsız — geçmişin amacı
    /// "az önce ne kopyaladım", uzun vadeli bir arşiv değil.
    private static let maxEntries = 40

    private var pollingTask: _Concurrency.Task<Void, Never>?
    private var lastChangeCount: Int
    private let fileURL: URL?
    private let imagesDirectory: URL?

    /// Parola yöneticileri (1Password, Bitwarden…) kopyaladıkları hassas
    /// veriyi bu türlerle işaretleyip "beni kaydetme" diyor —
    /// nspasteboard.org'daki de facto standart. Bunlara uyan hiçbir şey
    /// geçmişe girmiyor.
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private init() {
        lastChangeCount = NSPasteboard.general.changeCount
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
        if let directory = base?.appendingPathComponent("GlassDo", isDirectory: true) {
            try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            fileURL = directory.appendingPathComponent("clipboard-history.json")
            let images = directory.appendingPathComponent("ClipboardImages", isDirectory: true)
            try? FileManager.default.createDirectory(at: images, withIntermediateDirectories: true)
            imagesDirectory = images
        } else {
            fileURL = nil
            imagesDirectory = nil
        }
        load()
    }

    /// Uygulama açılışında bir kez çağrılır.
    func startMonitoring() {
        guard pollingTask == nil else { return }
        pollingTask = _Concurrency.Task { [weak self] in
            while !_Concurrency.Task.isCancelled {
                try? await _Concurrency.Task.sleep(for: Self.pollInterval)
                guard !_Concurrency.Task.isCancelled else { return }
                self?.pollPasteboardIfNeeded()
            }
        }
    }

    private func pollPasteboardIfNeeded() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        capture(from: pasteboard)
    }

    private func capture(from pasteboard: NSPasteboard) {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return }
        let types = Set(items.flatMap(\.types))
        guard !types.contains(Self.concealedType),
              !types.contains(Self.transientType),
              !types.contains(Self.autoGeneratedType)
        else { return }

        // Görsel önce denenir: bir görsel kopyalandığında pano genelde
        // hem görsel hem de yardımcı bir metin temsili taşıyabiliyor —
        // ikisini de tek girdi olarak eklemek yerine görsel önceliklidir.
        if let image = NSImage(pasteboard: pasteboard),
           let tiff = image.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            addImageEntry(png)
            return
        }

        if let text = pasteboard.string(forType: .string)?
            .trimmingCharacters(in: .whitespacesAndNewlines),
            !text.isEmpty {
            addTextEntry(text)
        }
    }

    private func addTextEntry(_ text: String) {
        guard entries.first?.kind != .text || entries.first?.text != text else { return }
        insert(ClipboardEntry(id: UUID(), kind: .text, text: text, imageFileName: nil, createdAt: Date()))
    }

    private func addImageEntry(_ pngData: Data) {
        guard let imagesDirectory else { return }
        let fileName = "\(UUID().uuidString).png"
        do {
            try pngData.write(to: imagesDirectory.appendingPathComponent(fileName), options: .atomic)
        } catch { return }
        insert(
            ClipboardEntry(id: UUID(), kind: .image, text: nil, imageFileName: fileName, createdAt: Date())
        )
    }

    private func insert(_ entry: ClipboardEntry) {
        entries.insert(entry, at: 0)
        while entries.count > Self.maxEntries {
            deleteImageFileIfNeeded(entries.removeLast())
        }
        persist()
    }

    func imageURL(for entry: ClipboardEntry) -> URL? {
        guard entry.kind == .image, let fileName = entry.imageFileName, let imagesDirectory else {
            return nil
        }
        return imagesDirectory.appendingPathComponent(fileName)
    }

    /// Girdiyi panoya geri yazar — geçmişteki bir şeyi yeniden kullanmanın
    /// tek yolu bu. Kendi yazdığımızı yeni bir girdi sanmayalım diye sayaç
    /// hemen ardından güncelleniyor.
    func copyToPasteboard(_ entry: ClipboardEntry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch entry.kind {
        case .text:
            guard let text = entry.text else { return }
            pasteboard.setString(text, forType: .string)
        case .image:
            guard let url = imageURL(for: entry), let image = NSImage(contentsOf: url) else { return }
            pasteboard.writeObjects([image])
        }
        lastChangeCount = pasteboard.changeCount
    }

    func remove(_ entry: ClipboardEntry) {
        guard let index = entries.firstIndex(of: entry) else { return }
        entries.remove(at: index)
        deleteImageFileIfNeeded(entry)
        persist()
    }

    func clearAll() {
        for entry in entries { deleteImageFileIfNeeded(entry) }
        entries.removeAll()
        persist()
    }

    private func deleteImageFileIfNeeded(_ entry: ClipboardEntry) {
        guard let url = imageURL(for: entry) else { return }
        try? FileManager.default.removeItem(at: url)
    }

    // MARK: - Kalıcılık

    private func persist() {
        guard let fileURL else { return }
        guard let data = try? JSONEncoder().encode(entries) else { return }
        try? data.write(to: fileURL, options: .atomic)
    }

    private func load() {
        guard let fileURL,
              let data = try? Data(contentsOf: fileURL),
              let decoded = try? JSONDecoder().decode([ClipboardEntry].self, from: data)
        else { return }
        entries = decoded
    }
}
